import type { Metadata } from 'next';
import './globals.css';
import TopNav from '@/widgets/TopNav';
import Footer from '@/widgets/Footer';
import { setInitialThemeMode } from '@/features/theme';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className={`mx-auto px-4 xl:px-0`}>
        <script
          dangerouslySetInnerHTML={{ __html: setInitialThemeMode }}
        ></script>
        <TopNav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
