import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import TopNav from '@/widgets/TopNav';
import Footer from '@/widgets/Footer';
import { setInitialThemeMode } from '@/features/theme';

const pretendard = localFont({
  src: [
    {
      path: '../../public/fonts/Pretendard-Bold.subset.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Pretendard-Semibold.subset.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Pretendard-Regular.subset.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Pretendard-Light.subset.woff2',
      weight: '300',
      style: 'normal',
    },
  ],
  variable: '--font-pretendard',
});

const jetBrainsMono = localFont({
  src: '../../public/fonts/JetBrainsMono-Regular.woff2',
  weight: '400',
  variable: '--font-jetBrainsMono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body
        className={`${pretendard.className} ${pretendard.variable} ${jetBrainsMono.variable} mx-auto px-4 xl:px-0`}
      >
        <script
          dangerouslySetInnerHTML={{ __html: setInitialThemeMode }}
        ></script>
        <TopNav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
